config/routes.rb
Rails.application.routes.draw do

  root             'events#index'

  get 'signin'  => 'sessions#new'
  delete 'signout' => 'sessions#destroy'
  get 'signup'  => 'users#new'

  resources :events, only: [:new, :create, :show, :index]
  resources :users, only: [:index, :new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  

end

app/models/attendent.rb
class Attendent < ActiveRecord::Base
  belongs_to :event_attendee, :class_name => "User"
  belongs_to :attended_event, :class_name => "Event"
end

app/models/event.rb
class Event < ActiveRecord::Base
	scope :upcoming, -> { where('date >= :today', {today: Time.now.to_date}) }
    scope :past,     -> { where('date <  :today', {today: Time.now.to_date}) }

	belongs_to :creator, :class_name => "User"
	has_many :attendees, :through => :attendents, :source => :event_attendee
	has_many :attendents, :foreign_key => :attended_event_id
end

app/models/user.rb
class User < ActiveRecord::Base
	before_create :create_remember_token
	has_many :created_events, :foreign_key => :creator_id, :class_name => "Event"
	has_many :attended_events, :through => :attendents
	has_many :attendents, :foreign_key => :event_attendee_id

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :sign_in, only: [:new, :create]

  def index
  	@events = Event.all
    @upcoming_events = Event.upcoming
    @past_events = Event.past
  end

  def new
  	@event = Event.new
  end

  def create
  	@event = current_user.created_events.build(event_params)
  	if @event.save
  	  flash[:success] = "Event successfully created"
      redirect_to root_path
  	else
  	  flash[:error] = "Error creating event"
  	  render 'new'
  	end 
  end

  def show
  	@event = Event.find_by(id: params[:id])
  end

  private
    def event_params
      params.require(:event).permit(:name, :location, :date)	
    end

    def sign_in
      redirect_to signin_path, notice: "Sign in to create Event" unless logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(name: params[:session][:name])
  	if user
  	  sign_in user
      flash[:success] = 'You have logged in'
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid name combo'
      render 'new'
    end
  end

  def destroy
  	sign_out
  	flash[:success] = 'You have logged out'
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
      UserMailer.welcome_email(@user).deliver_now
      redirect_to root_path
  	else
  	  render 'new'
  	end
  end

  def show
    @user = User.find(params[:id])
    @events = @user.created_events
    @upcoming_events = @user.attended_events.upcoming
    @past_events = @user.attended_events.past
  end

  private
    def user_params
  	  params.require(:user).permit(:name, :email, :password_digest)	 							 
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
  	remember_token = User.new_remember_token
  	cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def current_user
  	remember_token = User.digest(cookies[:remember_token])
  	#if current user isn't nil, it equals vv
  	@current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
  	@current_user = user
  end

  def sign_out
  	cookies.delete(:remember_token)
  	current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_attended_event.html.erb
<li>
  <%= link_to event.name, event %>
</li>

app/views/events/_event.html.erb
<li>
  <%= link_to event.name, event %>
</li>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<% if @past_events.any? %>
  <p> Past events: </p>
  <%= render 'shared/table', object: @past_events %>
<% end %>

<% if @upcoming_events.any? %>
  <p> Upcoming events: </p>
  <%= render 'shared/table', object: @upcoming_events %>
<% end %>

app/views/events/new.html.erb
<p>Create a new Event</p>

<%= form_for @event do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :location %>
  <%= f.text_field :location %><br>

  <%= f.label :date %>
  <%= f.datetime_select :date %><br>

  <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<p> Creator: <%= @event.creator.name %></p>

<p> Event name: <%= @event.name %></p>

<p> Location: <%= @event.location %></p>

<p> Date and time: <%= @event.date %></p>

<p> Attendents: 
	<% @event.attendees.each do |x| %>
		<li> <%= x.name %> </li>
	<% end %>
</p>

app/views/layouts/_header.html.erb
<%= link_to "Create User", signup_path %>
<%= link_to "Events", events_path %>
<%= link_to "Users", users_path %>

<% if logged_in? %>
    <%= link_to "Profile Page", current_user %>
	<%= link_to "Sign out", signout_path, method: "delete" %>
	<%= link_to "Create new event", new_event_path %> 
<% else %>
	<%= link_to "Sign in", signin_path %> 
<% end %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>
<%= yield %>

</body>
</html>

app/views/shared/_table.html.erb
<% object.each do |event| %>
  <li>
  	<%= link_to event.name, event %>
  </li>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
</li>

app/views/users/index.html.erb
All Users:
<%= render @users %>

app/views/users/new.html.erb
<p>Create an account</p>

<%= form_for @user do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :email %>
  <%= f.email_field :email %><br>

  <%= f.label :password %>
  <%= f.password_field :password_digest %><br>

  <%= f.submit "Sign up" %>
<% end %>

app/views/users/show.html.erb
<p> Name: <%= @user.name %></p>

<p> Email: <%= @user.email %></p>

<% if @events.any? %>
  <p><%= @user.name %>'s created events:</p>
  <%= render 'shared/table', object: @events %>
<% end %>

<% if @past_events.any? %>
  <p><%= @user.name %>'s attended past events:</p>
  <%= render 'shared/table', object: @past_events %>
<% end %>

<% if @upcoming_events.any? %>
  <p><%= @user.name %>'s attended upcoming events:</p>
  <%= render 'shared/table', object: @upcoming_events %>
<% end %>